<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Premium Jasmine Rice',
                'category' => 'premium',
                'description' => 'Aromatic, long-grain rice with a subtle floral fragrance. Perfect for everyday meals and special occasions.',
                'price' => 850.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
                'rating' => 4.9,
                'reviews_count' => 128,
                'tags' => ['Best Seller', 'Aromatic'],
                'in_stock' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Long Grain White Rice',
                'category' => 'standard',
                'description' => 'Classic, fluffy rice that stays separate when cooked. Ideal for daily cooking.',
                'price' => 650.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'reviews_count' => 95,
                'tags' => ['Popular'],
                'in_stock' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Brown Rice',
                'category' => 'specialty',
                'description' => 'Nutritious whole grain rice with a nutty flavor. High in fiber and essential nutrients.',
                'price' => 750.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'reviews_count' => 67,
                'tags' => ['Healthy Choice', 'Whole Grain'],
                'in_stock' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Glutinous Rice',
                'category' => 'specialty',
                'description' => 'Sticky rice perfect for traditional Filipino desserts like suman and biko.',
                'price' => 900.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'reviews_count' => 54,
                'tags' => ['For Desserts'],
                'in_stock' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Basmati Rice',
                'category' => 'premium',
                'description' => 'Extra-long grain rice with a distinctive aroma. Perfect for biryani and pilaf dishes.',
                'price' => 1200.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400&h=300&fit=crop',
                'rating' => 4.9,
                'reviews_count' => 82,
                'tags' => ['Premium', 'Imported'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Red Rice',
                'category' => 'specialty',
                'description' => 'Naturally colored rice with a unique earthy flavor. Rich in antioxidants.',
                'price' => 950.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
                'rating' => 4.5,
                'reviews_count' => 38,
                'tags' => ['Healthy Choice'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'Organic White Rice',
                'category' => 'organic',
                'description' => 'Certified organic rice grown without pesticides or chemical fertilizers.',
                'price' => 1100.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'reviews_count' => 45,
                'tags' => ['Organic', 'Chemical-Free'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Organic Brown Rice',
                'category' => 'organic',
                'description' => 'Certified organic whole grain brown rice. The healthiest choice for your family.',
                'price' => 1250.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&h=300&fit=crop',
                'rating' => 4.9,
                'reviews_count' => 56,
                'tags' => ['Organic', 'Whole Grain'],
                'in_stock' => false,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'Dinorado Rice',
                'category' => 'premium',
                'description' => 'Filipino heritage rice known for its soft texture and slightly sweet taste.',
                'price' => 980.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'reviews_count' => 72,
                'tags' => ['Local Favorite'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Sinandomeng Rice',
                'category' => 'standard',
                'description' => 'Popular Filipino rice variety with a soft, slightly sticky texture when cooked.',
                'price' => 720.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'reviews_count' => 89,
                'tags' => ['Local Favorite', 'Soft Texture'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'NFA Rice',
                'category' => 'standard',
                'description' => 'Affordable quality rice for everyday meals. Great value for money.',
                'price' => 480.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop',
                'rating' => 4.2,
                'reviews_count' => 156,
                'tags' => ['Budget Friendly'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'Black Rice',
                'category' => 'premium',
                'description' => 'Also known as forbidden rice, rich in antioxidants with a unique nutty flavor.',
                'price' => 1350.00,
                'unit' => '25kg',
                'image' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'reviews_count' => 34,
                'tags' => ['Premium', 'Superfood'],
                'in_stock' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
